import * as fs from 'fs';
import * as path from 'path';
import { ArchitectureStore } from '../architecture/architecture-store';
import { DecisionStore } from '../decisions/decision-store';
import { GraphStore } from '../architecture/graph-store';
import { WorkspaceLoader, WorkspaceConfig } from './workspace-loader';

export interface AiContextDeps {
  architectureStore: ArchitectureStore;
  decisionStore: DecisionStore;
  graphStore: GraphStore;
  rootPath: string;
  projectName: string;
}

const EOS_MARKER_START = '<!-- EOS:START — Auto-generated by Engineering OS. Edit conventions in eos.workspace.yaml -->';
const EOS_MARKER_END = '<!-- EOS:END -->';

export class AiContextGenerator {
  private workspace: WorkspaceConfig | null;

  constructor(private deps: AiContextDeps) {
    const loader = new WorkspaceLoader(deps.rootPath);
    this.workspace = loader.load();
  }

  async generateClaudeMd(): Promise<string> {
    const lines: string[] = [];

    lines.push(`# ${this.deps.projectName} — Engineering OS Managed`);
    lines.push('');
    lines.push('This project uses Engineering OS (EOS) as its knowledge layer. EOS has pre-indexed the entire codebase, architecture, conventions, decisions, and cross-service dependencies.');
    lines.push('');
    lines.push('## MANDATORY: Use EOS tools for ALL code tasks');
    lines.push('');
    lines.push('| When you want to... | Use this EOS tool | NOT this |');
    lines.push('|---|---|---|');
    lines.push('| Understand the project before starting | `eos_context` | Exploring files with Read/grep |');
    lines.push('| Find where something is implemented | `eos_search` | grep, find, Explore agent |');
    lines.push('| Check architecture/service boundaries | `eos_architecture` | Reading random files to infer |');
    lines.push('| Know what conventions to follow | `eos_conventions` | Guessing from existing code |');
    lines.push('| Check if a decision was already made | `eos_recall_decision` | Asking the user |');
    lines.push('| See what depends on what | `eos_dependencies` | Manually tracing imports |');
    lines.push('| Check impact before changing an interface | `eos_impact` | Hoping nothing breaks |');
    lines.push('| Find coding patterns to follow | `eos_patterns` | Scanning for similar code |');
    lines.push('| Plan a feature implementation | `eos_plan` | Creating a plan from scratch |');
    lines.push('| Validate code against standards | `eos_validate` | Manual review |');
    lines.push('| Run security review | `eos_security_scan` | Manual OWASP check |');
    lines.push('| Remember something for next time | `eos_learn` | Forgetting between sessions |');
    lines.push('| Recall past learnings | `eos_recall_skills` | Rediscovering the same thing |');
    lines.push('');
    lines.push('## Rules');
    lines.push('');
    lines.push('1. **ALWAYS call `eos_context` FIRST** before starting any task. It returns the full project gist — architecture, routes, conventions, decisions, cross-repo dependencies.');
    lines.push('2. **NEVER use grep/find/Explore** to understand the codebase. EOS has already indexed everything. Use `eos_search` instead.');
    lines.push('3. **NEVER make architecture decisions** without calling `eos_recall_decision` first — the decision may already exist.');
    lines.push('4. **NEVER change a shared interface** without calling `eos_impact` — other services may depend on it.');
    lines.push('5. **ALWAYS follow conventions** from `eos_conventions` — do not infer or guess patterns.');
    lines.push('6. **ALWAYS use `eos_search`** before writing new utilities — the function may already exist.');
    lines.push('7. **ALWAYS call `eos_learn`** when you discover something about this codebase (gotcha, pattern, connection) — it persists for future sessions.');
    lines.push('8. **ALWAYS call `eos_recall_skills`** at the start of a task — past sessions may have learned relevant skills.');

    return lines.join('\n');
  }

  async generateCursorRules(): Promise<Map<string, string>> {
    const files = new Map<string, string>();

    // eos-system.md — steering instructions (ALWAYS generated)
    const sysLines = [
      '# Engineering OS — Use EOS MCP tools for all tasks',
      '',
      'This project is managed by Engineering OS. Use these MCP tools:',
      '',
      '- `eos_context` — CALL FIRST before any task. Returns full architecture, routes, conventions.',
      '- `eos_search` — Use instead of grep/find. Pre-indexed and cross-repo.',
      '- `eos_conventions` — Coding standards. Follow them.',
      '- `eos_recall_decision` — Check before making architecture choices.',
      '- `eos_impact` — Check before changing shared interfaces.',
      '- `eos_patterns` — Find existing patterns to follow before writing new code.',
      '',
      'Do NOT explore the codebase manually. Do NOT guess conventions. Ask EOS.',
    ];
    files.set('eos-system.md', sysLines.join('\n'));

    // eos-conventions.md
    const conventions = await this.getConventions();
    if (conventions.length > 0) {
      const lines = ['# Project Conventions', '', 'Follow these conventions in all code changes:', ''];
      for (const conv of conventions) {
        lines.push(`## ${conv.name}`);
        lines.push(conv.rule);
        lines.push('');
      }
      files.set('eos-conventions.md', lines.join('\n'));
    }

    // eos-architecture.md
    const archLines = this.getArchitectureLines();
    if (archLines.length > 0) {
      const lines = [
        '# Project Architecture', '',
        `Project: ${this.deps.projectName}`,
        this.buildProjectSummaryLine(), '',
        ...archLines, '',
      ];
      files.set('eos-architecture.md', lines.join('\n'));
    }

    // eos-decisions.md
    const decisions = await this.getDecisions();
    if (decisions.length > 0) {
      const lines = ['# Engineering Decisions', '', 'These decisions are made. Do not propose alternatives unless new information is presented.', ''];
      for (const d of decisions) {
        lines.push(`## ${d.title}`);
        lines.push(`Decision: ${d.decision}`);
        if (d.rationale) lines.push(`Rationale: ${d.rationale}`);
        lines.push('');
      }
      files.set('eos-decisions.md', lines.join('\n'));
    }

    // eos-service-map.md (from graph JSON if available)
    const serviceMapPath = path.join(this.deps.rootPath, '.eos', 'graph', 'service-map.json');
    if (fs.existsSync(serviceMapPath)) {
      try {
        const data = JSON.parse(fs.readFileSync(serviceMapPath, 'utf-8'));
        if (data.services?.length > 0) {
          const lines = this.buildServiceMapMarkdown(data);
          files.set('eos-service-map.md', lines);
        }
      } catch { /* skip if malformed */ }
    }

    return files;
  }

  async generateCopilotInstructions(): Promise<string> {
    // Copilot does NOT have MCP — must include actual knowledge, not steering
    const sections: string[] = [];
    sections.push(`# ${this.deps.projectName}`);
    sections.push('');
    sections.push(this.buildProjectSummaryLine());
    sections.push('');

    const conventions = await this.getConventions();
    if (conventions.length > 0) {
      sections.push('## Conventions (MUST follow)');
      for (const conv of conventions.slice(0, 10)) {
        sections.push(`- **${conv.name}:** ${conv.rule}`);
      }
      sections.push('');
    }

    const archLines = this.getArchitectureLines();
    if (archLines.length > 0) {
      sections.push('## Architecture');
      sections.push(...archLines);
      sections.push('');
    }

    const decisions = await this.getDecisions();
    if (decisions.length > 0) {
      sections.push('## Decisions (do not re-debate or propose alternatives)');
      for (const d of decisions.slice(0, 7)) {
        sections.push(`- **${d.title}:** ${d.decision}`);
        if (d.rationale) sections.push(`  Why: ${d.rationale.slice(0, 100)}`);
      }
      sections.push('');
    }

    if (this.workspace && this.workspace.repos.length > 0) {
      sections.push('## Related Services');
      for (const repo of this.workspace.repos) {
        sections.push(`- ${repo.name}${repo.role ? ` (${repo.role})` : ''}`);
      }
      sections.push('');
    }

    return sections.join('\n');
  }

  async generateWindsurfRules(): Promise<string> {
    // Windsurf HAS MCP — use steering approach same as Claude
    const lines: string[] = [];
    lines.push(`# ${this.deps.projectName} — Engineering OS Managed`);
    lines.push('');
    lines.push('This project uses Engineering OS (EOS). Call EOS MCP tools for all code tasks:');
    lines.push('');
    lines.push('- `eos_context` — ALWAYS call first. Returns architecture, routes, conventions, decisions.');
    lines.push('- `eos_search` — Use instead of grep/find. Pre-indexed, cross-repo aware.');
    lines.push('- `eos_conventions` — Coding standards for this project.');
    lines.push('- `eos_recall_decision` — Check before making architecture choices.');
    lines.push('- `eos_impact` — Check before changing shared interfaces.');
    lines.push('');
    lines.push('Do not explore the codebase manually. EOS has the answers.');
    return lines.join('\n');
  }

  // --- File writing with marker support ---

  async writeClaudeMd(outputPath: string): Promise<void> {
    const content = await this.generateClaudeMd();
    this.writeWithMarkers(outputPath, content);
  }

  async writeCursorRules(rulesDir: string): Promise<string[]> {
    const rules = await this.generateCursorRules();
    if (!fs.existsSync(rulesDir)) fs.mkdirSync(rulesDir, { recursive: true });

    const written: string[] = [];
    for (const [filename, content] of rules) {
      fs.writeFileSync(path.join(rulesDir, filename), content, 'utf-8');
      written.push(filename);
    }
    return written;
  }

  async writeCopilotInstructions(outputPath: string): Promise<void> {
    const content = await this.generateCopilotInstructions();
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    this.writeWithMarkers(outputPath, content);
  }

  async writeWindsurfRules(outputPath: string): Promise<void> {
    const content = await this.generateWindsurfRules();
    this.writeWithMarkers(outputPath, content);
  }

  // --- Private helpers ---

  private writeWithMarkers(filePath: string, generatedContent: string): void {
    const markedContent = `${EOS_MARKER_START}\n${generatedContent}\n${EOS_MARKER_END}`;

    if (!fs.existsSync(filePath)) {
      fs.writeFileSync(filePath, markedContent, 'utf-8');
      return;
    }

    const existing = fs.readFileSync(filePath, 'utf-8');
    const startIdx = existing.indexOf(EOS_MARKER_START);
    const endIdx = existing.indexOf(EOS_MARKER_END);

    if (startIdx !== -1 && endIdx !== -1) {
      const before = existing.slice(0, startIdx);
      const after = existing.slice(endIdx + EOS_MARKER_END.length);
      fs.writeFileSync(filePath, before + markedContent + after, 'utf-8');
    } else {
      const separator = existing.endsWith('\n') ? '\n' : '\n\n';
      fs.writeFileSync(filePath, existing + separator + markedContent + '\n', 'utf-8');
    }
  }

  private buildProjectSummaryLine(): string {
    const parts: string[] = [];
    if (this.workspace?.type) parts.push(this.workspace.type);

    try {
      const stats = this.deps.graphStore.getStats();
      if (stats.services > 0) parts.push(`${stats.services} services`);
      if (stats.connections > 0) parts.push(`${stats.connections} connections`);
    } catch { /* graph not initialized */ }

    return parts.length > 0 ? parts.join(' | ') : '';
  }

  private getArchitectureLines(): string[] {
    const lines: string[] = [];
    try {
      const connections = this.deps.graphStore.getAllConnections();
      const services = this.deps.graphStore.getAllServices();
      if (connections.length === 0) return lines;

      const bySource = new Map<string, string[]>();
      for (const conn of connections) {
        const source = services.find((s) => s.id === conn.sourceService);
        const target = services.find((s) => s.id === conn.targetService);
        if (!source || !target) continue;
        if (!bySource.has(source.serviceName)) bySource.set(source.serviceName, []);
        bySource.get(source.serviceName)!.push(target.serviceName);
      }

      for (const [source, targets] of bySource) {
        lines.push(`- ${source} → ${targets.join(', ')}`);
      }
    } catch { /* graph not available */ }

    return lines;
  }

  private async getConventions(): Promise<Array<{ name: string; rule: string }>> {
    // Prefer workspace conventions (VCS-tracked, team-shared)
    if (this.workspace && this.workspace.conventions.length > 0) {
      return this.workspace.conventions;
    }

    // Fall back to discovered conventions from architecture store
    try {
      const discovered = await this.deps.architectureStore.getConventions();
      return discovered.map((c) => ({ name: c.name, rule: c.rule || c.description }));
    } catch {
      return [];
    }
  }

  private async getDecisions(): Promise<Array<{ title: string; decision: string; rationale?: string }>> {
    // Prefer workspace decisions (VCS-tracked)
    if (this.workspace && this.workspace.decisions.length > 0) {
      return this.workspace.decisions;
    }

    // Fall back to decision store
    try {
      const all = await this.deps.decisionStore.list({ status: 'accepted' });
      return all.slice(0, 5).map((d) => ({
        title: d.title,
        decision: d.decision,
        rationale: d.rationale,
      }));
    } catch {
      return [];
    }
  }

  private buildServiceMapMarkdown(data: { services: any[]; connections: any[]; contracts: any[] }): string {
    const lines: string[] = ['# Service Dependency Map', ''];
    lines.push('Changes to shared interfaces require coordination across services.');
    lines.push('');

    if (data.connections.length > 0) {
      lines.push('## Dependencies');
      for (const c of data.connections) {
        lines.push(`- ${c.sourceService} → ${c.targetService} [${c.protocol}]`);
      }
      lines.push('');
    }

    if (data.contracts.length > 0) {
      lines.push('## Contracts');
      for (const c of data.contracts) {
        lines.push(`- ${c.type}: ${c.filePath} (${c.repoName})`);
      }
    }

    return lines.join('\n');
  }
}
